### ISSUE TITLE
Python2 - Automatic FAS submission script broken

### ISSUE THREAD

**Issue by jflory7** [rodrigc/kernel-tests#1]
Part of the intent of updating this script is to ensure functionality with both Python2 and Python3. In this instance, when the changes are run using Python2, the kernel regression tests run successfully, but the scripts to enable automatic submission of logs are broken.

```
$ ./runtests.sh 
Test suite called with default
./default/mq-memory-corruption                                   PASS    
./default/stack-randomness                                       PASS    
./default/modsign                                                SKIP    
./default/cachedrop                                              SKIP    
./default/paxtest                                                FAIL    
./default/timer-overhead                                         PASS    
./default/memfd                                                  PASS    
./default/libhugetlbfs                                           SKIP    
./default/selinux-dac-controls                                   SKIP    
./default/insert_leap_second                                     SKIP    
./default/posix_timers                                           PASS    
./default/sysfs-perms                                            PASS    

Test suite complete                                              FAIL    

Your log file is being submitted
FAS password: 
Traceback (most recent call last):
  File "./fedora_submit.py", line 44, in <module>
    password=password
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 291, in login
    openid_insecure=self.openid_insecure)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidproxyclient.py", line 129, in openid_login
    'Un-expected openid provider asked: %s' % response.url)
fedora.client.FedoraServiceError: Un-expected openid provider asked: https://apps.fedoraproject.org/kerneltest/
```

**Comment by rodrigc** [comment]
I cannot reproduce that failure.  Here is what I did from a Fedora 23 system.

```
sudo dnf install fedora-client
git clone -b python3 https://github.com/rodrigc/kernel-tests
cd kernel-tests
cp config.example .config
```

In .config, I changed this line:

```
submit=anonymous
```
I then ran:

```
./runtests.sh
```
I got this:

```
Script started on Fri 18 Dec 2015 05:29:19 PM PST
Test suite called with default
./default/cachedrop                                              SKIP    
./default/insert_leap_second                                     SKIP    
./default/libhugetlbfs                                           SKIP    
./default/memfd                                                  PASS    
./default/modsign                                                SKIP    
./default/mq-memory-corruption                                   PASS    
./default/paxtest                                                PASS    
./default/posix_timers                                           PASS    
./default/selinux-dac-controls                                   SKIP    
./default/stack-randomness                                       PASS    
./default/sysfs-perms                                            PASS    
./default/timer-overhead                                         PASS    

Test suite complete                                              PASS    

Your log file is being submitted
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>417 Expectation Failed</title>
</head><body>
<h1>Expectation Failed</h1>
<p>The expectation given in the Expect request-header
field could not be met by this server.
The client sent<pre>
    Expect: 100-continue
</pre>
</p><p>Only the 100-continue expectation is supported.</p>
<hr>
<address>Apache/2.4.6 (Red Hat Enterprise Linux) Server at apps.fedoraproject.org Port 443</address>
</body></html>
```

I think there is a problem on the backend server, which has nothing to do with the patch I
submitted.

**Comment by abadger** [comment]
Note:  you need to install python-fedora not fedora-client.  (I don't believe fedora-client is a package).

**Comment by jflory7** [comment]
@rodrigc I ran mine slightly differently, I was trying to authenticate in the CLI.

Here is what I did on my Fedora 23 system:
```
git clone -b python3 https://github.com/rodrigc/kernel-tests
cd kernel-tests
cp config.example .config
```
In `.config`, I changed this line:
```
submit=authenticated
username='jflory7'
# password=''
```
I then ran:
```
./runtests.sh
```

My output looks like this when I use that branch.
```
Your log file is being submitted
FAS password: 
Traceback (most recent call last):
  File "./fedora_submit.py", line 55, in <module>
    print(req.text)
  File "/usr/lib/python2.7/site-packages/munch/__init__.py", line 128, in __getattr__
    raise AttributeError(k)
AttributeError: text
```

**Comment by rodrigc** [comment]
@jflory7: Looks like that problem existed in the script before my changes.  It was fixed with:
                 https://git.fedorahosted.org/cgit/kernel-tests.git/commit/?id=bbc0fd7f6f5085547b4604b7bca4ba61b138df7b

Can you check out the code from: https://git.fedorahosted.org/git/kernel-tests.git
and try again?  @jmflinuxtx committed my fixes upstream.

**Comment by jflory7** [comment]
@rodrigc I see now. I pulled those changes down and still have the same result.
```
Your log file is being submitted
FAS password: 
Traceback (most recent call last):
  File "./fedora_submit.py", line 45, in <module>
    password=password
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 293, in login
    openid_insecure=self.openid_insecure)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidproxyclient.py", line 129, in openid_login
    'Un-expected openid provider asked: %s' % response.url)
fedora.client.FedoraServiceError: Un-expected openid provider asked: https://apps.fedoraproject.org/kerneltest/
```

It seems like now this issue might be out of the scope of this repo. Feel free to close this issue if you wish.

**Comment by rodrigc** [comment]
@jflory7: You may want to contact Justin Forbes (  @jmflinuxtx ) and ask him directly, or file a bug, similar to: https://bugzilla.redhat.com/show_bug.cgi?id=1293015
Justin was very responsive in the bug.

I don't have an account, so can't test the openid authentication stuff.

Thanks for providing feedback.

**Comment by jmflinuxtx** [comment]
Actually, that particular error just started showing up today. It wasn't
there last week, I am guessing it is a server issue, code has not changed
on the client side. The Python 3 fixups do not seem to impact the issue at
all as I still get it with a checkout from before those commits.

**Comment by jflory7** [comment]
Thanks for the info, @jmflinuxtx. I will try again later this week and see if anything changes.
